---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by houn.
--- DateTime: 2020/6/22 20:25
--- 游戏主应用类

local super = nil
---@class App
local App = class("App", super)

function App:init()
    ---@type EventBeat
    self.updateBeat = LuaClass.EventBeat("UpdateBeat")
    ---@type EventBeat
    self.fixedUpdateBeat = LuaClass.EventBeat("FixedUpdateBeat")
    ---@type EventBeat
    self.lateUpdateBeat = LuaClass.EventBeat("LateUpdateBeat")

    self.autoReleaseObjects = {}

    self.mainCamera = LuaClass.GameObject.Find("Main Camera"):GetComponent(typeof(LuaClass.Camera))

    self:initManager()

    self:initModule()

    self:gameStart()
end

function App:autoRelease(gameObject)
    self.autoReleaseObjects[gameObject] = gameObject
end

function App:cancelAutoRelease(gameObject)
    self.autoReleaseObjects[gameObject] = nil
end

function App:update(deltaTime)
    self.updateBeat:update(dt)
    for go, _ in ipairs(self.autoReleaseObjects) do
        self.autoReleaseObjects[go] = nil
        if isValid(go) then
            LuaClass.Object.Destroy(go)
        end
    end
    --每一帧清理需要自动释放的表
    table.recoveryTable()
end

function App:fixedUpdate(fixedDeltaTime)
    self.fixedUpdateBeat:update(fixedDeltaTime)
end

function App:lateUpdate()
    self.lateUpdateBeat:update()
end

function App:addEnterFrameHandler(enterFrameHandler)
    self.updateBeat:add(enterFrameHandler)
end

function App:removeEnterFrameHandler(enterFrameHandler)
    self.updateBeat:remove(enterFrameHandler)
end

function App:initManager()
    ---@type EventDispatcher
    self.globalEventDispatcher = LuaClass.EventDispatcher()
    ---@type UiManager
    self.uiManager = LuaClass.UiManager()
    ---@type KeyManager
    self.keyManager = LuaClass.KeyManager()
end

function App:initModule()
    ---@type MainModule
    self.mainModule = LuaClass.MainModule()
    ---@type BasicsModule
    self.basicsModule = LuaClass.BasicsModule()
    ---@type BagModule
    self.bagModule = LuaClass.BagModule()
end

function App:gameStart()
    ---@type GameStart
    local gameStart = LuaClass.GameStart:NewGameObject()
end

function App:quit()
    self._isQuitting = true
    print("退出游戏")
end

function App:isQuitting()
    return self._isQuitting
end

function App:restart()
    print("重新启动游戏")
end

return App

