---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by houn.
--- DateTime: 2020/6/10 20:43
---
---Des Lua主要入口
---
package.cpath = package.cpath .. ';C:/Users/houn/AppData/Roaming/JetBrains/IntelliJIdea2020.1/plugins/intellij-emmylua/classes/debugger/emmy/windows/x64/?.dll'
local dbg = require('emmy_core')
dbg.tcpListen('localhost', 9966)
function __G__UPDATE__(deltaTime)
    if isValid(App) then
        App:update(deltaTime)
    end
end

function __G__FIXEDUPDATE__(fixedDeltaTime)
    if isValid(App) then
        App:fixedUpdate(fixedDeltaTime)
    end
end

function __G__LATEUPDATE__()
    if isValid(App) then
        App:lateUpdate()
    end
end

function __G__QUIT__()
    if isValid(App) then
        App:quit()
    end
end

function main()
    require("Core.CoreInit")
    require("Common.Util.LogUtil")
    ---@type App
    App = LuaClass.App()
    App:init()
    print("===============init game==============")
end

main()

