---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by houn.
--- DateTime: 2020/6/22 20:26
---

--FairyGUI
---@type FairyGUI.EventContext
LuaClass.GuiEventContext = CS.FairyGUI.EventContext
---@type FairyGUI.EventListener
LuaClass.GuiEventListener = CS.FairyGUI.EventListener
---@type FairyGUI.EventDispatcher
LuaClass.GuiEventDispatcher = CS.FairyGUI.EventDispatcher
---@type FairyGUI.InputEvent
LuaClass.GuiInputEvent = CS.FairyGUI.InputEvent
---@type FairyGUI.NTexture
LuaClass.GuiNTexture = CS.FairyGUI.NTexture
---@type FairyGUI.Container
LuaClass.GuiContainer = CS.FairyGUI.Container
---@type FairyGUI.Image
LuaClass.GuiImage = CS.FairyGUI.Image
---@type FairyGUI.Stage
LuaClass.GuiStage = CS.FairyGUI.Stage
---@type FairyGUI.Controller
LuaClass.GuiController = CS.FairyGUI.Controller
---@type FairyGUI.GObject
LuaClass.GuiGObject = CS.FairyGUI.GObject
---@type FairyGUI.GoWrapper
LuaClass.GuiGoWrapper = CS.FairyGUI.GoWrapper
---@type FairyGUI.GGraph
LuaClass.GuiGGraph = CS.FairyGUI.GGraph
---@type FairyGUI.GGroup
LuaClass.GuiGGroup = CS.FairyGUI.GGroup
---@type FairyGUI.GImage
LuaClass.GuiGImage = CS.FairyGUI.GImage
---@type FairyGUI.GLoader
LuaClass.GuiGLoader = CS.FairyGUI.GLoader
---@type FairyGUI.GMovieClip
LuaClass.GuiGMovieClip = CS.FairyGUI.GMovieClip
---@type FairyGUI.TextFormat
LuaClass.GuiTextFormat = CS.FairyGUI.TextFormat
---@type FairyGUI.GTextField
LuaClass.GuiGTextField = CS.FairyGUI.GTextField
---@type FairyGUI.GRichTextField
LuaClass.GuiGRichTextField = CS.FairyGUI.GRichTextField
---@type FairyGUI.GTextInput
LuaClass.GuiGTextInput = CS.FairyGUI.GTextInput
---@type FairyGUI.GComponent
LuaClass.GuiGComponent = CS.FairyGUI.GComponent
---@type FairyGUI.GList
LuaClass.GuiGList = CS.FairyGUI.GList
---@type FairyGUI.GRoot
LuaClass.GuiGRoot = CS.FairyGUI.GRoot
---@type FairyGUI.GLabel
LuaClass.GuiGLabel = CS.FairyGUI.GLabel
---@type FairyGUI.GButton
LuaClass.GuiGButton = CS.FairyGUI.GButton
---@type FairyGUI.GComboBox
LuaClass.GuiGComboBox = CS.FairyGUI.GComboBox
---@type FairyGUI.GProgressBar
LuaClass.GuiGProgressBar = CS.FairyGUI.GProgressBar
---@type FairyGUI.GSlider
LuaClass.GuiGSlider = CS.FairyGUI.GSlider
---@type FairyGUI.PopupMenu
LuaClass.GuiPopupMenu = CS.FairyGUI.PopupMenu
---@type FairyGUI.ScrollPane
LuaClass.GuiScrollPane = CS.FairyGUI.ScrollPane
---@type FairyGUI.Transition
LuaClass.GuiTransition = CS.FairyGUI.Transition
---@type FairyGUI.UIPackage
LuaClass.GuiUIPackage = CS.FairyGUI.UIPackage
---@type FairyGUI.Window
LuaClass.GuiWindow = CS.FairyGUI.Window
---@type FairyGUI.GObjectPool
LuaClass.GuiGObjectPool = CS.FairyGUI.GObjectPool
---@type FairyGUI.Relations
LuaClass.GuiRelations = CS.FairyGUI.Relations
LuaClass.GuiRelationType = CS.FairyGUI.RelationType
---@type FairyGUI.UIPanel
LuaClass.GuiUIPanel = CS.FairyGUI.UIPanel
---@type FairyGUI.UIPainter
LuaClass.GuiUIPainter = CS.FairyGUI.UIPainter
---@type FairyGUI.TypingEffect
LuaClass.GuiTypingEffect = CS.FairyGUI.TypingEffect
---@type FairyGUI.UIConfig
LuaClass.GuiUIConfig = CS.FairyGUI.UIConfig
LuaClass.GuiPopupDirection = CS.FairyGUI.PopupDirection
---@type FairyGUI.DragDropManager
LuaClass.GuiDragDropManager = CS.FairyGUI.DragDropManager
---@type FairyGUI.EllipseMesh
LuaClass.GuiEllipseMesh = CS.FairyGUI.EllipseMesh
---@type FairyGUI.PolygonMesh
LuaClass.GuiPolygonMesh = CS.FairyGUI.PolygonMesh
---@type FairyGUI.LineMesh
LuaClass.GuiLineMesh = CS.FairyGUI.LineMesh
---@type FairyGUI.VertexBuffer
LuaClass.GuiVertexBuffer = CS.FairyGUI.VertexBuffer
---@type FairyGUI.GPathPoint
LuaClass.GuiGPathPoint = CS.FairyGUI.GPathPoint
---@type FairyGUI.GTween
LuaClass.GuiGTween = CS.FairyGUI.GTween
---@type FairyGUI.UIObjectFactory
LuaClass.GuiUIObjectFactory = CS.FairyGUI.UIObjectFactory
---@type FairyGUI.BlurFilter
LuaClass.GuiBlurFilter = CS.FairyGUI.BlurFilter
---@type FairyGUI.SwipeGesture
LuaClass.GuiSwipeGesture = CS.FairyGUI.SwipeGesture
---@type FairyGUI.LongPressGesture
LuaClass.GuiLongPressGesture = CS.FairyGUI.LongPressGesture
---@type FairyGUI.PinchGesture
LuaClass.GuiPinchGesture = CS.FairyGUI.PinchGesture
---@type FairyGUI.RotationGesture
LuaClass.GuiRotationGesture = CS.FairyGUI.RotationGesture
LuaClass.EaseType = CS.FairyGUI.EaseType
LuaClass.AutoSizeType = CS.FairyGUI.AutoSizeType
LuaClass.ScrollBarDisplayType = CS.FairyGUI.ScrollBarDisplayType
LuaClass.PopupDirection = CS.FairyGUI.PopupDirection
LuaClass.BlendMode = CS.FairyGUI.BlendMode
LuaClass.ToolSet = CS.FairyGUI.Utils.ToolSet




--Unity
--- @type UnityEngine.AnimationCurve
LuaClass.AnimationCurve = CS.UnityEngine.AnimationCurve
--- @type UnityEngine.Vector2
LuaClass.Vector2 = CS.UnityEngine.Vector2
--- @type UnityEngine.Vector3
LuaClass.Vector3 = CS.UnityEngine.Vector3
--- @type UnityEngine.Mathf
LuaClass.Mathf = CS.UnityEngine.Mathf
LuaClass.Quaternion = CS.UnityEngine.Quaternion
LuaClass.Space = CS.UnityEngine.Space
LuaClass.Object = CS.UnityEngine.Object
--- @type UnityEngine.GameObject
LuaClass.GameObject = CS.UnityEngine.GameObject
--- @type UnityEngine.Color
LuaClass.Color = CS.UnityEngine.Color
--- @type UnityEngine.Time
LuaClass.Time = CS.UnityEngine.Time
--- @type UnityEngine.RaycastHit
LuaClass.RaycastHit = CS.UnityEngine.RaycastHit
--- @type UnityEngine.Physics
LuaClass.Physics = CS.UnityEngine.Physics
--- @type UnityEngine.Application
LuaClass.Application = CS.UnityEngine.Application
LuaClass.RuntimePlatform = CS.UnityEngine.RuntimePlatform
--- @type UnityEngine.Debug
LuaClass.CsDebug = CS.UnityEngine.Debug
---@type UnityEngine.Rect
LuaClass.Rect = CS.UnityEngine.Rect
LuaClass.Sprite = CS.UnityEngine.Sprite
LuaClass.TextMesh = CS.UnityEngine.TextMesh
---@type UnityEngine.LayerMask
LuaClass.LayerMask = CS.UnityEngine.LayerMask
LuaClass.Animator = CS.UnityEngine.Animator
LuaClass.Animation = CS.UnityEngine.Animation
LuaClass.AnimatorCullingMode = CS.UnityEngine.AnimatorCullingMode
LuaClass.RuntimeAnimatorController = CS.UnityEngine.RuntimeAnimatorController
LuaClass.NavMeshAgent = CS.UnityEngine.NavMeshAgent
LuaClass.PolygonCollider2D = CS.UnityEngine.PolygonCollider2D
LuaClass.KeyCode = CS.UnityEngine.KeyCode
--- @type UnityEngine.Input
LuaClass.Input = CS.UnityEngine.Input
LuaClass.Renderer = CS.UnityEngine.Renderer
LuaClass.RenderMode = CS.UnityEngine.RenderMode
LuaClass.Camera = CS.UnityEngine.Camera
--- @type UnityEngine.Screen
LuaClass.Screen = CS.UnityEngine.Screen
LuaClass.GUIText = CS.UnityEngine.GUIText
--- @type UnityEngine.RectTransform
LuaClass.RectTransform = CS.UnityEngine.RectTransform
LuaClass.RectTransform.Edge = CS.UnityEngine.RectTransform.Edge
--- @type UnityEngine.Transform
LuaClass.Transform = CS.UnityEngine.Transform
LuaClass.Text = CS.UnityEngine.UI.Text
LuaClass.Image = CS.UnityEngine.UI.Image
LuaClass.RawImage = CS.UnityEngine.UI.RawImage
LuaClass.Button = CS.UnityEngine.UI.Button
LuaClass.CanvasGroup = CS.UnityEngine.CanvasGroup
LuaClass.Canvas = CS.UnityEngine.Canvas
--- @type UnityEngine.Mathf
-- LuaClass.Mathf 			= CS.UnityEngine.Mathf
LuaClass.CharacterController = CS.UnityEngine.CharacterController
LuaClass.SkinnedMeshRenderer = CS.UnityEngine.SkinnedMeshRenderer
LuaClass.Mesh = CS.UnityEngine.Mesh
LuaClass.NavMesh = CS.UnityEngine.NavMesh
LuaClass.NavMeshPath = CS.UnityEngine.NavMeshPath
LuaClass.RectOffset = CS.UnityEngine.RectOffset
LuaClass.Toggle = CS.UnityEngine.UI.Toggle
LuaClass.ScrollRect = CS.UnityEngine.UI.ScrollRect
--- @type UnityEngine.UI.LayoutUtility
LuaClass.LayoutUtility = CS.UnityEngine.UI.LayoutUtility
LuaClass.LayoutElement = CS.UnityEngine.UI.LayoutElement
LuaClass.LayoutRebuilder = CS.UnityEngine.UI.LayoutRebuilder
LuaClass.VerticalLayoutGroup = CS.UnityEngine.UI.VerticalLayoutGroup
--- @type UnityEngine.UI.GridLayoutGroup
LuaClass.GridLayoutGroup = CS.UnityEngine.UI.GridLayoutGroup
LuaClass.MaskableGraphic = CS.UnityEngine.UI.MaskableGraphic
LuaClass.SphereCollider = CS.UnityEngine.SphereCollider
LuaClass.Collider = CS.UnityEngine.Collider
LuaClass.CapsuleCollider = CS.UnityEngine.CapsuleCollider
LuaClass.PlayerPrefs = CS.UnityEngine.PlayerPrefs
LuaClass.EventSystems = CS.UnityEngine.EventSystems
LuaClass.GUIUtility = CS.UnityEngine.GUIUtility
LuaClass.RenderTexture = CS.UnityEngine.RenderTexture
LuaClass.UFilterModule = CS.UnityEngine.FilterMode
LuaClass.GL = CS.UnityEngine.GL
LuaClass.Texture2D = CS.UnityEngine.Texture2D
LuaClass.TextureFormat = CS.UnityEngine.TextureFormat
LuaClass.RenderTextureFormat = CS.UnityEngine.RenderTextureFormat
LuaClass.RenderTextureReadWrite = CS.UnityEngine.RenderTextureReadWrite
LuaClass.Shader = CS.UnityEngine.Shader
LuaClass.EventSystem = CS.UnityEngine.EventSystem
LuaClass.RenderSettings = CS.UnityEngine.RenderSettings
LuaClass.MeshFilter = CS.UnityEngine.MeshFilter
LuaClass.ShadowCastingMode = CS.UnityEngine.Rendering.ShadowCastingMode
LuaClass.MeshRenderer = CS.UnityEngine.MeshRenderer
LuaClass.ParticleSystem = CS.UnityEngine.ParticleSystem
LuaClass.Material = CS.UnityEngine.Material
LuaClass.StaticBatchingUtility = CS.UnityEngine.StaticBatchingUtility
LuaClass.FogMode = CS.UnityEngine.FogMode
LuaClass.RenderTextureFormat = CS.UnityEngine.RenderTextureFormat
---@type UnityEngine.SceneManagement.SceneManager
LuaClass.SceneManager = CS.UnityEngine.SceneManagement.SceneManager
LuaClass.SpriteRenderer = CS.UnityEngine.SpriteRenderer
LuaClass.LineRenderer = CS.UnityEngine.LineRenderer
LuaClass.SystemInfo = CS.UnityEngine.SystemInfo
LuaClass.LightmapSettings = CS.UnityEngine.LightmapSettings
LuaClass.LightmapsMode = CS.UnityEngine.LightmapsMode
LuaClass.RectTransformUtility = CS.UnityEngine.RectTransformUtility
--在运行时将General GI的Directional Mode的设置为Non-Directional
LuaClass.LightmapSettings.lightmapsMode = LuaClass.LightmapsMode.NonDirectional
--
LuaClass.QualitySettings = CS.UnityEngine.QualitySettings
LuaClass.QualitySettings.lodBias = 1
--- @type UnityEngine.Profiler
LuaClass.Profiler = CS.UnityEngine.Profiler
LuaClass.ThreadPriority = CS.UnityEngine.ThreadPriority
--- @type UnityEngine.TextAnchor
LuaClass.TextAnchor = CS.UnityEngine.TextAnchor

LuaClass.Light = CS.UnityEngine.Light
LuaClass.Resources = CS.UnityEngine.Resources
LuaClass.TextAsset = CS.UnityEngine.TextAsset

LuaClass.VideoPlayer = CS.UnityEngine.Video.VideoPlayer


---FairyStudy
LuaClass.CsLogUtil = CS.FairyStudy.LogUtil
LuaClass.CsAppConfig = CS.FairyStudy.AppConfig