
-------------------------------------------------------------------------------
--
-- 这个文件是所有的功能模块对应的lua文件列表 
-- 由工具自动生成,请勿手工修改
--
--------------------------------------------------------------------------------
---@class LuaClassList
LuaClassList = 
{
	app                                     = "App",
	appconfig                               = "AppConfig",
	debug                                   = "Debug",
	gameconfig                              = "GameConfig",
	gamestart                               = "GameStart",
	main                                    = "Main",
	baseluacomponent                        = "Common.Component.BaseLuaComponent",
	gameobjectcomponent                     = "Common.Component.GameObjectComponent",
	globalconstant                          = "Common.Constant.GlobalConstant",
	moduleconstant                          = "Common.Constant.ModuleConstant",
	uiconstant                              = "Common.Constant.UiConstant",
	eventbeat                               = "Common.Event.EventBeat",
	eventdispatcher                         = "Common.Event.EventDispatcher",
	keymanager                              = "Common.Manager.KeyManager",
	poolmanager                             = "Common.Manager.PoolManager",
	timermanager                            = "Common.Manager.TimerManager",
	uimanager                               = "Common.Manager.UiManager",
	basemodule                              = "Common.Module.BaseModule",
	baseui                                  = "Common.Module.UiModule.BaseUi",
	assetpathutilex                         = "Common.Util.AssetPathUtilEx",
	logutil                                 = "Common.Util.LogUtil",
	objectpool                              = "Common.Util.ObjectPool",
	stringuntil                             = "Common.Util.StringUntil",
	uioperateuntil                          = "Common.Util.UiOperateUntil",
	coreinit                                = "Core.CoreInit",
	csharpbinding                           = "Core.CSharpBinding",
	functions                               = "Core.Functions",
	luaclass                                = "Core.LuaClass",
	luaclasslist                            = "Core.LuaClassList",
	luaclasstips                            = "Core.LuaClassTips",
	extension                               = "Core.Extension.Extension",
	extensioninit                           = "Core.Extension.ExtensionInit",
	gameobjectex                            = "Core.Extension.GameObjectEx",
	bagmodule                               = "Module.Bag.BagModule",
	bagview                                 = "Module.Bag.BagView",
	basicsmodule                            = "Module.Basics.BasicsModule",
	basicsview                              = "Module.Basics.BasicsView",
	bundleusagemodule                       = "Module.BundleUsage.BundleUsageModule",
	bundleusageview                         = "Module.BundleUsage.BundleUsageView",
	cooldownmodule                          = "Module.CoolDown.CoolDownModule",
	cooldownview                            = "Module.CoolDown.CoolDownView",
	curvemodule                             = "Module.Curve.CurveModule",
	curveview                               = "Module.Curve.CurveView",
	cutscenemodule                          = "Module.CutScene.CutSceneModule",
	cutsceneview                            = "Module.CutScene.CutSceneView",
	emitcomponent                           = "Module.EmitNumbers.EmitComponent",
	emitnumbersmodule                       = "Module.EmitNumbers.EmitNumbersModule",
	emitnumbersview                         = "Module.EmitNumbers.EmitNumbersView",
	emojimodule                             = "Module.Emoji.EmojiModule",
	emojiview                               = "Module.Emoji.EmojiView",
	extensionmodule                         = "Module.Extension.ExtensionModule",
	extensionview                           = "Module.Extension.ExtensionView",
	filtermodule                            = "Module.Filter.FilterModule",
	filterview                              = "Module.Filter.FilterView",
	gesturemodule                           = "Module.Gesture.GestureModule",
	gestureview                             = "Module.Gesture.GestureView",
	guidemodule                             = "Module.Guide.GuideModule",
	guideview                               = "Module.Guide.GuideView",
	headbarmodule                           = "Module.HeadBar.HeadBarModule",
	headbarview                             = "Module.HeadBar.HeadBarView",
	hittestmodule                           = "Module.HitTest.HitTestModule",
	hittestview                             = "Module.HitTest.HitTestView",
	joystickmodule                          = "Module.JoyStick.JoyStickModule",
	joystickview                            = "Module.JoyStick.JoyStickView",
	looplistmodule                          = "Module.LoopList.LoopListModule",
	looplistview                            = "Module.LoopList.LoopListView",
	mainmodule                              = "Module.MainScene.MainModule",
	mainview                                = "Module.MainScene.MainView",
	modalwaitingmodule                      = "Module.ModalWaiting.ModalWaitingModule",
	modalwaitingview                        = "Module.ModalWaiting.ModalWaitingView",
	modelmodule                             = "Module.Model.ModelModule",
	modelview                               = "Module.Model.ModelView",
	particlesmodule                         = "Module.Particles.ParticlesModule",
	particlesview                           = "Module.Particles.ParticlesView",
	perspectivemodule                       = "Module.Perspective.PerspectiveModule",
	perspectiveview                         = "Module.Perspective.PerspectiveView",
	pulltorefreshmodule                     = "Module.PullToRefresh.PullToRefreshModule",
	pulltorefreshview                       = "Module.PullToRefresh.PullToRefreshView",
	rendertexturemodule                     = "Module.RenderTexture.RenderTextureModule",
	rendertextureview                       = "Module.RenderTexture.RenderTextureView",
	scrollpanemodule                        = "Module.ScrollPane.ScrollPaneModule",
	scrollpaneview                          = "Module.ScrollPane.ScrollPaneView",
	transitionmodule                        = "Module.Transition.TransitionModule",
	transitionview                          = "Module.Transition.TransitionView",
	treeviewmodule                          = "Module.TreeView.TreeViewModule",
	treeviewview                            = "Module.TreeView.TreeViewView",
	turncardmodule                          = "Module.TurnCard.TurnCardModule",
	turncardview                            = "Module.TurnCard.TurnCardView",
	turnpagemodule                          = "Module.TurnPage.TurnPageModule",
	turnpageview                            = "Module.TurnPage.TurnPageView",
	typingeffectmodule                      = "Module.TypingEffect.TypingEffectModule",
	typingeffectview                        = "Module.TypingEffect.TypingEffectView",
	virtuallistmodule                       = "Module.VirtualList.VirtualListModule",
	virtuallistview                         = "Module.VirtualList.VirtualListView",
	bagwindow                               = "Module.Windows.BagWindow",
	windowsa                                = "Module.Windows.WindowsA",
	windowsb                                = "Module.Windows.WindowsB",

}

DatatableExtension = 
{

}


LuaClass = {}