---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by houn.
--- DateTime: 2020/6/21 22:24
---

--lua文件访问入口
-- LuaClass={}
-- 加载文件列表

-- 初始化LuaClassList，后面再次访问LuaClass的时候，就会直接require class
require "Core.LuaClassList"

local function initLuaClass()
    local metaTable = {}
    metaTable.__index = function(t, key)
        local keyLow = string.lower(key)
        if LuaClassList[keyLow] == nil then
            error("Effor: No Lua Script:" .. key)
            return nil
        end
        t[key] = require(LuaClassList[keyLow])
        return t[key]
    end
    setmetatable(LuaClass, metaTable)
end

local function preLoadClass()
    local preLoadClassTable = {

    }
    local temp
    for _, className in ipairs(preLoadClassTable) do
        temp = LuaClass[className]
    end
end

function __G__RELOAD_ALL_MODULE__()
    for i, v in ipairs(LuaClassList) do
        package.loaded[v] = nil
    end
    LuaClass = {}
    initLuaClass()
    preLoadClass()
end

function LuaClass.clearLua(className)
    local low = string.lower(className)
    if LuaClassList[low] == nil then
        error("Effor: No Lua Script:" .. key)
        return
    end
    package.loaded[LuaClassList[low]] = nil
end
initLuaClass()
preLoadClass()