---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by houn.
--- DateTime: 2020/6/10 20:43
---
---Des Lua主要入口
---

function __G__UPDATE__(deltaTime)
    if isValid(App) then
        App:update(deltaTime)
    end
end

function __G__FIXEDUPDATE__(fixedDeltaTime)
    if isValid(App) then
        App:fixedUpdate(fixedDeltaTime)
    end
end

function __G__LATEUPDATE__()
    if isValid(App) then
        App:lateUpdate()
    end
end

function __G__QUIT__()
    if isValid(App) then
        App:quit()
    end
end

function main()
    require("Common.Util.LogUtil")
    require("Core.CoreInit")
    ---@type App
    App = LuaClass.App()
    App:init()
    xlua.isNull(App)
    local import_type = xlua.import_type
    --xlua.getmetatable("GameObject")
    print("===============init game==============")
end

main()

